/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { usePlanner } from '../context/PlannerContext';
import { 
  Sparkles, User, Mail, Phone, GraduationCap, Search, ArrowRight, 
  ArrowLeft, CheckCircle2, BookOpen, Calendar, ClipboardList, Plus, Trash2, HelpCircle
} from 'lucide-react';
import { Subject, TimetableEvent, Assignment, Exam, Note } from '../types';

export default function OnboardingScreen() {
  const { initializeOnboardedData } = usePlanner();

  // Wizard Steps: 1 = Personal info, 2 = Academic details, 3 = AI Syllabus Generation, 4 = Review & Confirm
  const [step, setStep] = useState<number>(1);
  
  // Step 1 Form States
  const [name, setName] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [phone, setPhone] = useState<string>('');
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});

  // Step 2 Form States
  const [selectedClass, setSelectedClass] = useState<string>('Class 10');
  const [selectedBoard, setSelectedBoard] = useState<string>('CBSE');
  const [otherBoard, setOtherBoard] = useState<string>('');
  const [customPreferences, setCustomPreferences] = useState<string>('');

  // Loading States for Step 3
  const [isLoadingSyllabus, setIsLoadingSyllabus] = useState<boolean>(false);
  const [syllabusError, setSyllabusError] = useState<string>('');
  const [loadingLog, setLoadingLog] = useState<string>('');

  // Step 4 Review States (generated by AI and editable by student)
  const [generatedSubjects, setGeneratedSubjects] = useState<Subject[]>([]);
  const [generatedTimetable, setGeneratedTimetable] = useState<TimetableEvent[]>([]);
  const [generatedAssignments, setGeneratedAssignments] = useState<Assignment[]>([]);
  const [generatedExams, setGeneratedExams] = useState<Exam[]>([]);
  const [generatedNotes, setGeneratedNotes] = useState<Note[]>([]);

  // Subject Creator Form (Optional editing in step 4)
  const [newSubName, setNewSubName] = useState<string>('');
  const [newSubColor, setNewSubColor] = useState<string>('#3B82F6');

  // List of standard boards
  const BOARDS = [
    { id: 'CBSE', name: 'CBSE (Central Board of Secondary Education)' },
    { id: 'ICSE', name: 'ICSE / ISC (Indian Certificate of Secondary Education)' },
    { id: 'State Board', name: 'State Board (State-specific Curriculum)' },
    { id: 'IB', name: 'IB (International Baccalaureate)' },
    { id: 'IGCSE', name: 'Cambridge IGCSE / A-Levels' }
  ];

  // List of standards
  const CLASSES = Array.from({ length: 12 }, (_, i) => `Class ${i + 1}`);

  // Color options for subjects
  const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#8B5CF6', '#EF4444', '#06B6D4', '#EC4899', '#14B8A6'];

  // Validate step 1
  const handleStep1Next = () => {
    const errors: Record<string, string> = {};
    if (!name.trim()) errors.name = 'Full name is required';
    if (!email.trim()) {
      errors.email = 'Gmail or Email address is required';
    } else if (!/\S+@\S+\.\S+/.test(email)) {
      errors.email = 'Please provide a valid email format';
    }
    if (!phone.trim()) {
      errors.phone = 'Phone number is required';
    } else if (phone.replace(/\D/g, '').length < 8) {
      errors.phone = 'Please enter a valid phone number';
    }

    if (Object.keys(errors).length > 0) {
      setFormErrors(errors);
      return;
    }

    setFormErrors({});
    setStep(2);
  };

  // Run Google-grounded AI search to create syllabus
  const handleFetchSyllabus = async () => {
    setIsLoadingSyllabus(true);
    setSyllabusError('');
    setStep(3);

    const actualBoard = selectedBoard === 'State Board' ? (otherBoard || 'State Board') : selectedBoard;

    // Loading status transitions for immersion
    const logs = [
      `Initializing Google Search APIs for ${actualBoard}...`,
      `Querying Google: "${actualBoard} ${selectedClass} latest official syllabus subjects curriculum"...`,
      `Extracting school curriculum from official board announcements...`,
      `Generating customized subjects list, estimated credits, and study plan...`,
      `Drafting relative school assignments, exam schedules, and revision materials...`,
      `Designing optimized 7-day school study timetable for ${selectedClass} students...`,
      `Assembling textbook-grade study notes and proof formulas...`
    ];

    let logIndex = 0;
    setLoadingLog(logs[0]);
    const logInterval = setInterval(() => {
      if (logIndex < logs.length - 1) {
        logIndex++;
        setLoadingLog(logs[logIndex]);
      }
    }, 1200);

    try {
      const response = await fetch('/api/ai/syllabus', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          email,
          phone,
          standard: selectedClass,
          board: actualBoard,
          customPreferences: customPreferences
        })
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || 'Failed to fetch syllabus.');
      }

      const data = await response.json();
      
      // Setup relative dates based on current live date
      const now = new Date();
      const formatDate = (daysOffset: number) => {
        const d = new Date();
        d.setDate(now.getDate() + daysOffset);
        return d.toISOString().split('T')[0];
      };

      // Map generated elements
      const subjects: Subject[] = data.subjects || [];
      
      const assignments: Assignment[] = (data.assignments || []).map((asg: any, index: number) => ({
        id: `asg-gen-${index}`,
        subjectId: asg.subjectId || (subjects[0]?.id || 'sub-1'),
        title: asg.title || 'Board Chapter Problem Set',
        dueDate: formatDate(asg.dueDateOffset !== undefined ? asg.dueDateOffset : 3),
        priority: asg.priority || 'medium',
        status: 'pending',
        notes: asg.notes || 'Based on standard syllabus reference.'
      }));

      const exams: Exam[] = (data.exams || []).map((ex: any, index: number) => ({
        id: `ex-gen-${index}`,
        subjectId: ex.subjectId || (subjects[0]?.id || 'sub-1'),
        title: ex.title || 'Unit Test Evaluation',
        examDate: formatDate(ex.examDateOffset !== undefined ? ex.examDateOffset : 10),
        notes: ex.notes || 'Covers first syllabus term.'
      }));

      const notes: Note[] = (data.notes || []).map((nt: any, index: number) => ({
        id: `note-gen-${index}`,
        subjectId: nt.subjectId || (subjects[0]?.id || 'sub-1'),
        title: nt.title || 'Curriculum Overview Lecture',
        content: nt.content || 'Notes content here.',
        createdAt: new Date().toISOString(),
        summary: nt.summary || 'Summary of textbook chapters.',
        keyPoints: nt.keyPoints || [],
        formulas: nt.formulas || []
      }));

      const timetable: TimetableEvent[] = (data.timetable || []).map((tt: any, index: number) => ({
        id: `tt-gen-${index}`,
        subjectId: tt.subjectId || (subjects[0]?.id || 'sub-1'),
        title: tt.title || 'Syllabus Focus',
        dayOfWeek: tt.dayOfWeek || 1,
        startTime: tt.startTime || '15:00',
        endTime: tt.endTime || '16:00',
        type: tt.type || 'study'
      }));

      setGeneratedSubjects(subjects);
      setGeneratedTimetable(timetable);
      setGeneratedAssignments(assignments);
      setGeneratedExams(exams);
      setGeneratedNotes(notes);

      clearInterval(logInterval);
      setStep(4);
    } catch (error: any) {
      console.error(error);
      setSyllabusError(error.message || 'Syllabus search failed. Please try again.');
      setStep(2);
    } finally {
      setIsLoadingSyllabus(false);
      clearInterval(logInterval);
    }
  };

  // Launch Dashboard
  const handleLaunchApp = () => {
    const finalUser = {
      id: `usr-${Date.now()}`,
      name: name,
      email: email,
      phone: phone,
      standard: selectedClass,
      board: selectedBoard === 'State Board' ? (otherBoard || 'State Board') : selectedBoard,
      isOnboarded: true,
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      school: `${selectedBoard === 'State Board' ? (otherBoard || 'State') : selectedBoard} Academy`,
      major: `${selectedClass} Syllabus`,
      streak: 1,
      lastActiveDate: new Date().toISOString().split('T')[0],
      totalHoursStudied: 0
    };

    initializeOnboardedData(
      finalUser,
      generatedSubjects,
      generatedTimetable,
      generatedAssignments,
      generatedExams,
      generatedNotes
    );
  };

  // Skip wizard to original preloaded Demo profile
  const handleSkipToDemo = () => {
    const demoUser = {
      id: 'usr-1',
      name: 'Alex Mercer',
      email: 'meghamane49@gmail.com',
      phone: '+91 98765 43210',
      standard: 'Class 10',
      board: 'CBSE',
      isOnboarded: true,
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      school: 'Pacific Tech Academy',
      major: 'Computer Science Stream',
      streak: 4,
      lastActiveDate: new Date().toISOString().split('T')[0],
      totalHoursStudied: 12.5
    };

    // Load original mock data lists
    const initialSubjects: Subject[] = [
      { id: 'sub-1', name: 'Calculus III', color: '#3B82F6', credits: 4, grade: 'A' },
      { id: 'sub-2', name: 'Computer Architecture', color: '#10B981', credits: 3, grade: 'B+' },
      { id: 'sub-3', name: 'Organic Chemistry', color: '#F59E0B', credits: 4, grade: 'A-' },
      { id: 'sub-4', name: 'Academic English', color: '#8B5CF6', credits: 2, grade: 'A' },
    ];

    const initialAssignments: Assignment[] = [
      {
        id: 'asg-1',
        subjectId: 'sub-1',
        title: 'Multivariable Integration Problem Set',
        dueDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
        priority: 'high',
        status: 'pending',
        notes: 'Focus heavily on polar coordinates and spherical transformations. Questions 4 to 12.'
      },
      {
        id: 'asg-2',
        subjectId: 'sub-2',
        title: 'Cache Simulator in C++',
        dueDate: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0],
        priority: 'high',
        status: 'pending',
        notes: 'Implement LRU and FIFO replacement policies. Ensure compile flags are configured for clean run.'
      }
    ];

    const initialExams: Exam[] = [
      {
        id: 'ex-1',
        subjectId: 'sub-1',
        title: 'Midterm II: Vector Calculus',
        examDate: new Date(Date.now() + 86400000 * 6).toISOString().split('T')[0],
        notes: 'Covers Green\'s Theorem, Stokes\' Theorem, and Divergence Theorem. Highly conceptual.'
      }
    ];

    const initialNotes: Note[] = [
      {
        id: 'note-1',
        subjectId: 'sub-1',
        title: 'Understand Green\'s Theorem',
        content: `Green's Theorem relates a line integral around a simple closed curve C to a double integral over the region D.\n∮_C (P dx + Q dy) = ∬_D (∂Q/∂x - ∂P/∂y) dA`,
        createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
        summary: "Green's Theorem bridges vector line integrals to double integrals.",
        keyPoints: ["Relates closed line integrals to double integrals", "Curve C must be counter-clockwise"],
        formulas: ["∮_C (P dx + Q dy) = ∬_D (∂Q/∂x - ∂P/∂y) dA"]
      }
    ];

    const initialTimetable: TimetableEvent[] = [
      { id: 'tt-1', subjectId: 'sub-1', title: 'Calculus Revision', dayOfWeek: 1, startTime: '09:00', endTime: '10:30', type: 'study' },
      { id: 'tt-2', subjectId: 'sub-2', title: 'Cache Design Work', dayOfWeek: 1, startTime: '14:00', endTime: '15:30', type: 'study' }
    ];

    initializeOnboardedData(
      demoUser,
      initialSubjects,
      initialTimetable,
      initialAssignments,
      initialExams,
      initialNotes
    );
  };

  // Step 4 Actions: Remove Subject
  const handleRemoveSubject = (id: string) => {
    setGeneratedSubjects(prev => prev.filter(s => s.id !== id));
    setGeneratedTimetable(prev => prev.filter(tt => tt.subjectId !== id));
    setGeneratedAssignments(prev => prev.filter(a => a.subjectId !== id));
    setGeneratedExams(prev => prev.filter(e => e.subjectId !== id));
    setGeneratedNotes(prev => prev.filter(n => n.subjectId !== id));
  };

  // Step 4 Actions: Add Subject manually
  const handleAddSubject = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newSubName.trim()) return;
    const newId = `sub-custom-${Date.now()}`;
    const newSubject: Subject = {
      id: newId,
      name: newSubName.trim(),
      color: newSubColor,
      credits: 3
    };
    setGeneratedSubjects(prev => [...prev, newSubject]);
    setNewSubName('');
  };

  return (
    <div className="min-h-screen w-screen bg-slate-50 flex items-center justify-center p-4 md:p-8 font-sans text-slate-800 relative overflow-y-auto selection:bg-indigo-100 selection:text-indigo-900">
      
      {/* Decorative gradient rings background */}
      <div className="absolute top-0 left-0 w-80 h-80 bg-indigo-200/20 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-96 h-96 bg-emerald-200/10 rounded-full blur-3xl translate-x-1/3 translate-y-1/3 pointer-events-none" />

      <div className="bg-white rounded-2xl border border-slate-200 shadow-xl w-full max-w-2xl overflow-hidden flex flex-col relative">
        
        {/* Top visual brand banner */}
        <div className="bg-indigo-950 text-white p-6 relative overflow-hidden flex items-center justify-between shrink-0">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-900 to-slate-900" />
          <div className="absolute -right-10 -bottom-10 opacity-10">
            <Sparkles className="w-48 h-48 text-indigo-400" />
          </div>
          <div className="relative z-10 flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-600 rounded-lg flex items-center justify-center shadow-md">
              <Sparkles className="w-5 h-5 text-white animate-pulse" />
            </div>
            <div>
              <h1 className="text-base font-bold tracking-tight uppercase">StudentHub</h1>
              <p className="text-[10px] text-indigo-200 font-bold tracking-wider uppercase">Syllabus Co-Pilot Registration</p>
            </div>
          </div>
          <div className="relative z-10 text-right hidden sm:block">
            <span className="text-xs bg-indigo-800/60 text-indigo-200 px-3 py-1 rounded-full border border-indigo-700/50 font-bold">
              Step {step} of 4
            </span>
          </div>
        </div>

        {/* Form area */}
        <div className="flex-1 p-6 md:p-8 overflow-y-auto max-h-[500px]">
          
          {/* STEP 1: PERSONAL INFORMATION */}
          {step === 1 && (
            <div className="space-y-6">
              <div className="text-center sm:text-left">
                <h2 className="text-lg font-extrabold text-slate-800 tracking-tight">Create Your Student Profile</h2>
                <p className="text-xs text-slate-500 mt-1">Provide your credentials to register with your Syllabus Co-Pilot.</p>
              </div>

              <div className="space-y-4">
                {/* Full name input */}
                <div>
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                    <User className="w-3.5 h-3.5 text-slate-400" />
                    Full Name
                  </label>
                  <input
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="e.g. Sarah Jenkins"
                    className={`w-full px-4 py-2.5 rounded-xl border bg-slate-50/50 text-xs text-slate-800 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20 transition ${
                      formErrors.name ? 'border-red-300 focus:border-red-500' : 'border-slate-200 focus:border-indigo-500'
                    }`}
                  />
                  {formErrors.name && (
                    <span className="text-[10px] text-red-500 font-medium mt-1 block">{formErrors.name}</span>
                  )}
                </div>

                {/* Gmail Address input */}
                <div>
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                    <Mail className="w-3.5 h-3.5 text-slate-400" />
                    Gmail ID / Email Address
                  </label>
                  <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="e.g. sarah.jenkins@gmail.com"
                    className={`w-full px-4 py-2.5 rounded-xl border bg-slate-50/50 text-xs text-slate-800 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20 transition ${
                      formErrors.email ? 'border-red-300 focus:border-red-500' : 'border-slate-200 focus:border-indigo-500'
                    }`}
                  />
                  {formErrors.email && (
                    <span className="text-[10px] text-red-500 font-medium mt-1 block">{formErrors.email}</span>
                  )}
                </div>

                {/* Phone Number input */}
                <div>
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                    <Phone className="w-3.5 h-3.5 text-slate-400" />
                    Phone Number
                  </label>
                  <input
                    type="tel"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    placeholder="e.g. +91 98765 43210"
                    className={`w-full px-4 py-2.5 rounded-xl border bg-slate-50/50 text-xs text-slate-800 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20 transition ${
                      formErrors.phone ? 'border-red-300 focus:border-red-500' : 'border-slate-200 focus:border-indigo-500'
                    }`}
                  />
                  {formErrors.phone && (
                    <span className="text-[10px] text-red-500 font-medium mt-1 block">{formErrors.phone}</span>
                  )}
                </div>
              </div>

              {/* Demo profile quick bypass button */}
              <div className="pt-4 border-t border-slate-100 flex flex-col items-center justify-center gap-2">
                <button
                  type="button"
                  onClick={handleSkipToDemo}
                  className="text-xs text-indigo-600 hover:text-indigo-800 hover:underline font-bold transition cursor-pointer flex items-center gap-1"
                >
                  <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
                  Skip onboarding & load standard Demo profile (Alex Mercer, Class 10 CBSE)
                </button>
                <p className="text-[10px] text-slate-400">Perfect for quick assessment of already cataloged data logs.</p>
              </div>
            </div>
          )}

          {/* STEP 2: ACADEMIC DETAILS */}
          {step === 2 && (
            <div className="space-y-6">
              <div className="text-center sm:text-left">
                <h2 className="text-lg font-extrabold text-slate-800 tracking-tight">Select Board & Standard</h2>
                <p className="text-xs text-slate-500 mt-1">Choose your curriculum standard up to 12th grade and school board.</p>
              </div>

              {syllabusError && (
                <div className="bg-red-50 border border-red-100 text-red-700 p-3.5 rounded-xl text-xs flex items-start gap-2">
                  <HelpCircle className="w-4 h-4 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold">Generation Error:</span> {syllabusError}
                  </div>
                </div>
              )}

              <div className="space-y-5">
                {/* Standard selector */}
                <div>
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                    <GraduationCap className="w-3.5 h-3.5 text-slate-400" />
                    Standard / Grade (Up to 12th)
                  </label>
                  <div className="grid grid-cols-3 sm:grid-cols-4 gap-2">
                    {CLASSES.map((cls) => {
                      const isSel = selectedClass === cls;
                      return (
                        <button
                          key={cls}
                          type="button"
                          onClick={() => setSelectedClass(cls)}
                          className={`py-2 px-1 text-center rounded-xl text-xs font-bold transition border cursor-pointer ${
                            isSel 
                              ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm' 
                              : 'bg-slate-50 border-slate-200 hover:bg-slate-100 text-slate-600'
                          }`}
                        >
                          {cls}
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* School Board selector */}
                <div>
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                    <BookOpen className="w-3.5 h-3.5 text-slate-400" />
                    School Examination Board
                  </label>
                  <div className="space-y-2">
                    {BOARDS.map((boardItem) => {
                      const isSel = selectedBoard === boardItem.id;
                      return (
                        <button
                          key={boardItem.id}
                          type="button"
                          onClick={() => setSelectedBoard(boardItem.id)}
                          className={`w-full text-left p-3.5 rounded-xl border flex items-center justify-between transition cursor-pointer ${
                            isSel
                              ? 'bg-indigo-50 border-indigo-200 text-indigo-900 ring-1 ring-indigo-500/20'
                              : 'bg-white border-slate-200 hover:bg-slate-50 text-slate-700'
                          }`}
                        >
                          <div className="flex items-center gap-3">
                            <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${isSel ? 'border-indigo-600' : 'border-slate-300'}`}>
                              {isSel && <div className="w-2.5 h-2.5 bg-indigo-600 rounded-full" />}
                            </div>
                            <span className="text-xs font-bold">{boardItem.name}</span>
                          </div>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* Other Board Text input if State Board is selected */}
                {selectedBoard === 'State Board' && (
                  <div className="pt-2 animate-fadeIn">
                    <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-1.5">
                      Specify State Board Name
                    </label>
                    <input
                      type="text"
                      value={otherBoard}
                      onChange={(e) => setOtherBoard(e.target.value)}
                      placeholder="e.g. Maharashtra State Board (HSC), Karnataka (KSEEB), UP Board"
                      className="w-full px-4 py-2.5 rounded-xl border border-slate-200 bg-slate-50/50 text-xs text-slate-800 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition"
                    />
                  </div>
                )}

                {/* Custom Preferences Text Area (or the user tells you) */}
                <div>
                  <label className="block text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
                    Syllabus Customization & Electives (Optional)
                  </label>
                  <p className="text-[10px] text-slate-400 mb-1.5">
                    Tell us what subjects or topics to prioritize or omit (e.g. "Focus on Science, ignore Sanskrit", "I am in Science stream: physics, chemistry, biology, math").
                  </p>
                  <textarea
                    value={customPreferences}
                    onChange={(e) => setCustomPreferences(e.target.value)}
                    placeholder="e.g. Add Computer Science elective, focus heavily on Algebra, omit Art syllabus..."
                    rows={2}
                    className="w-full px-4 py-2.5 rounded-xl border border-slate-200 bg-slate-50/50 text-xs text-slate-800 focus:outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition resize-none"
                  />
                </div>
              </div>
            </div>
          )}

          {/* STEP 3: LOADING SCREEN */}
          {step === 3 && (
            <div className="py-12 flex flex-col items-center justify-center text-center space-y-6">
              <div className="relative">
                <div className="w-16 h-16 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin" />
                <div className="absolute inset-0 flex items-center justify-center">
                  <Sparkles className="w-6 h-6 text-indigo-600 animate-pulse" />
                </div>
              </div>

              <div className="space-y-2 max-w-sm">
                <h3 className="font-extrabold text-slate-800 text-sm">Searching Google Grounded Syllabus...</h3>
                <p className="text-xs text-indigo-600 font-bold bg-indigo-50 px-3 py-1.5 rounded-lg border border-indigo-100 inline-block animate-pulse">
                  {loadingLog}
                </p>
                <p className="text-[10px] text-slate-400">
                  This connects live to search engines to gather your exact examination board curriculum details and map school timetables.
                </p>
              </div>
            </div>
          )}

          {/* STEP 4: REVIEW & CONFIRM */}
          {step === 4 && (
            <div className="space-y-6">
              <div>
                <h2 className="text-lg font-extrabold text-slate-800 tracking-tight">Review Your AI-Generated Syllabus</h2>
                <p className="text-xs text-slate-500 mt-1">
                  Google Search found the following standard curriculum structure for <span className="font-bold text-indigo-600">{selectedBoard === 'State Board' ? (otherBoard || 'State Board') : selectedBoard} {selectedClass}</span>. You can review, add, or remove subjects below.
                </p>
              </div>

              {/* Subject Grid */}
              <div className="space-y-4">
                <div>
                  <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                    <BookOpen className="w-4 h-4 text-indigo-600" />
                    Subjects List ({generatedSubjects.length})
                  </h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                    {generatedSubjects.map((sub) => (
                      <div 
                        key={sub.id} 
                        className="bg-slate-50 border border-slate-200 rounded-xl p-3 flex items-center justify-between"
                      >
                        <div className="flex items-center gap-2.5">
                          <div className="w-3.5 h-3.5 rounded-full" style={{ backgroundColor: sub.color }} />
                          <span className="text-xs font-bold text-slate-800">{sub.name}</span>
                        </div>
                        <button
                          type="button"
                          onClick={() => handleRemoveSubject(sub.id)}
                          className="p-1 hover:bg-slate-200 text-slate-400 hover:text-red-500 rounded-lg transition cursor-pointer"
                          title="Delete Subject"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Add Custom Subject */}
                <form onSubmit={handleAddSubject} className="bg-slate-50 rounded-xl p-4 border border-slate-200 flex flex-col sm:flex-row gap-2 items-center">
                  <div className="w-full sm:flex-1">
                    <input
                      type="text"
                      value={newSubName}
                      onChange={(e) => setNewSubName(e.target.value)}
                      placeholder="Add an elective / custom subject..."
                      className="w-full px-3 py-1.5 rounded-lg border border-slate-200 bg-white text-xs text-slate-800 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                    />
                  </div>
                  <div className="flex gap-2 w-full sm:w-auto justify-between items-center shrink-0">
                    <div className="flex gap-1.5">
                      {COLORS.map((col) => (
                        <button
                          key={col}
                          type="button"
                          onClick={() => setNewSubColor(col)}
                          className={`w-5 h-5 rounded-full transition relative shrink-0 cursor-pointer ${
                            newSubColor === col ? 'ring-2 ring-indigo-500 scale-110' : 'hover:scale-105'
                          }`}
                          style={{ backgroundColor: col }}
                        />
                      ))}
                    </div>
                    <button
                      type="submit"
                      className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs py-1.5 px-3 rounded-lg flex items-center gap-1 cursor-pointer shrink-0"
                    >
                      <Plus className="w-3.5 h-3.5" /> Add
                    </button>
                  </div>
                </form>

                {/* Summary boxes of generated items */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
                  <div className="bg-indigo-50/50 border border-indigo-100 p-3 rounded-xl text-center">
                    <Calendar className="w-5 h-5 text-indigo-600 mx-auto mb-1" />
                    <span className="block text-lg font-extrabold text-indigo-900 leading-tight">
                      {generatedTimetable.length}
                    </span>
                    <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">
                      Study Slots
                    </span>
                  </div>

                  <div className="bg-emerald-50/50 border border-emerald-100 p-3 rounded-xl text-center">
                    <ClipboardList className="w-5 h-5 text-emerald-600 mx-auto mb-1" />
                    <span className="block text-lg font-extrabold text-emerald-900 leading-tight">
                      {generatedAssignments.length}
                    </span>
                    <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">
                      Assignments
                    </span>
                  </div>

                  <div className="bg-red-50/50 border border-red-100 p-3 rounded-xl text-center">
                    <Sparkles className="w-5 h-5 text-red-600 mx-auto mb-1" />
                    <span className="block text-lg font-extrabold text-red-900 leading-tight">
                      {generatedExams.length}
                    </span>
                    <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">
                      Upcoming Exams
                    </span>
                  </div>

                  <div className="bg-amber-50/50 border border-amber-100 p-3 rounded-xl text-center">
                    <BookOpen className="w-5 h-5 text-amber-600 mx-auto mb-1" />
                    <span className="block text-lg font-extrabold text-amber-900 leading-tight">
                      {generatedNotes.length}
                    </span>
                    <span className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">
                      Study Notes
                    </span>
                  </div>
                </div>

                <div className="bg-indigo-950 text-white rounded-xl p-4 border border-indigo-900 text-xs flex gap-3">
                  <div className="bg-indigo-800 p-2 rounded-lg h-fit">
                    <CheckCircle2 className="w-5 h-5 text-indigo-200" />
                  </div>
                  <div>
                    <h4 className="font-extrabold text-indigo-100 mb-0.5">Ready to Initialize!</h4>
                    <p className="text-[11px] text-indigo-200/80 leading-relaxed">
                      All subjects and syllabus timelines are set. This will initialize your StudentHub with real board curriculum logs, upcoming exam notices, and optimized daily timetables.
                    </p>
                  </div>
                </div>

              </div>
            </div>
          )}

        </div>

        {/* Footer controls */}
        {step !== 3 && (
          <div className="bg-slate-50 px-6 py-4 border-t border-slate-200 flex justify-between items-center shrink-0">
            {step > 1 ? (
              <button
                type="button"
                onClick={() => setStep(prev => prev - 1)}
                className="bg-white hover:bg-slate-100 border border-slate-300 text-slate-600 font-bold text-xs py-2 px-4 rounded-xl flex items-center gap-1.5 transition cursor-pointer"
              >
                <ArrowLeft className="w-4 h-4" /> Back
              </button>
            ) : (
              <div />
            )}

            {step === 1 ? (
              <button
                type="button"
                onClick={handleStep1Next}
                className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs py-2 px-5 rounded-xl flex items-center gap-1.5 transition shadow-sm cursor-pointer"
              >
                Continue <ArrowRight className="w-4 h-4" />
              </button>
            ) : step === 2 ? (
              <button
                type="button"
                onClick={handleFetchSyllabus}
                className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs py-2 px-5 rounded-xl flex items-center gap-1.5 transition shadow-sm cursor-pointer"
              >
                Search & Generate Syllabus <Sparkles className="w-4 h-4" />
              </button>
            ) : step === 4 ? (
              <button
                type="button"
                onClick={handleLaunchApp}
                className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs py-2 px-6 rounded-xl flex items-center gap-1.5 transition shadow-md cursor-pointer animate-bounce"
              >
                Initialize Co-Pilot Dashboard 🚀
              </button>
            ) : (
              <div />
            )}
          </div>
        )}

      </div>
    </div>
  );
}
